In [5]:
# Dependencies
import requests
import json

# Google API Key
# fort_key = "1640f0eb-6047-426b-8705-28b4724d8489"



# url = "https://api.fortnitetracker.com/v1/store"
# headers = {"TRN-Api-Key": "1c7e220d-6bd4-4754-9b89-21ce52b227d0"}
# r = requests.get(url, headers=headers).json()

# print(json.dumps(r, indent=4, sort_keys=True))

In [6]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0].columns

Index(['PLAYER_ID', 'SEASON_ID', 'LEAGUE_ID', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'PLAYER_AGE', 'GP', 'GS', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A',
       'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL',
       'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [7]:
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

adv_path = "NBAadvanced.csv"
per_path = "NBAper36.csv"

#sa
ca_player = pd.read_csv(california_path, encoding='utf8')
per_data = pd.read_csv(per_path, encoding='utf8')

In [8]:
per_data.head()

,Rk,Player,Age,Tm,G,GS,MP,FG,FGA,FG%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Steven Adams,26,OKC,58,58,1564,6.0,10.2,0.591,...,0.590,4.5,8.0,12.5,3.2,1.2,1.5,2.0,2.6,14.6
1,2,Bam Adebayo,22,MIA,65,65,2235,6.6,11.6,0.567,...,0.690,2.7,8.3,11.0,5.4,1.3,1.4,3.0,2.6,17.0
2,3,LaMarcus Aldridge,34,SAS,53,53,1754,8.0,16.3,0.493,...,0.827,2.1,5.9,8.0,2.6,0.7,1.8,1.5,2.6,20.5
3,4,Nickeil Alexander-Walker,21,NOP,41,0,501,5.5,16.3,0.339,...,0.607,0.6,5.2,5.7,5.3,0.8,0.5,2.9,3.3,15.2
4,5,Grayson Allen,24,MEM,30,0,498,5.7,12.7,0.449,...,0.857,0.4,4.4,4.8,3.1,0.4,0.1,1.7,2.6,16.0